language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
script:
  - npm run lint
  - npm run lintTests
  - npm test
  - npm run mutate
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"